[build]
  command = "pipenv install"
  publish = "public"

[build.environment]
  PIPENV_VENV_IN_PROJECT = "true"

[[plugins]]
  package = "@netlify/plugin-functions-install-python"

[plugins.inputs]
  runtime = "3.10"